# Уменьшает задержку обработки escape-последовательностей.
# Делает отклик tmux более быстрым, особенно в Neovim и при выходе из insert-mode.
set-option -sg escape-time 10

# Включает поддержку focus events.
# Некоторые приложения внутри tmux могут реагировать на получение и потерю фокуса окна.
set-option -g focus-events on

# Устанавливает префикс tmux на Ctrl+a вместо стандартного Ctrl+b.
set -g prefix C-a

# Убирает старый префикс Ctrl+b.
unbind C-b

# Позволяет отправить Ctrl+a в приложение внутри tmux по двойному нажатию Ctrl+a.
bind C-a send-prefix
