# Уменьшает задержку обработки escape-последовательностей.
# Делает отклик tmux более быстрым, особенно в Neovim и при выходе из insert-mode.
set-option -sg escape-time 10

# Включает поддержку focus events.
# Некоторые приложения внутри tmux могут реагировать на получение и потерю фокуса окна.
set-option -g focus-events on

# Устанавливает префикс tmux на Ctrl+a вместо стандартного Ctrl+b.
set -g prefix C-a

# Убирает старый префикс Ctrl+b.
unbind C-b

# Позволяет отправить Ctrl+a в приложение внутри tmux по двойному нажатию Ctrl+a.
bind C-a send-prefix

# Быстрая перезагрузка конфига (Prefix + r).
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

set -s set-clipboard off

# Vim-подобные клавиши в командной строке tmux.
set -g status-keys vi

# Vim-подобные клавиши в copy mode.
setw -g mode-keys vi

# В copy mode:
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
# Копирование сразу в системный буфер обмена.
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi Escape send -X cancel

